#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl stop  keysas-firewall || true
            systemctl disable keysas-firewall || true
        fi
        ;;
esac

#DEBHELPER#
exit 0
